FROM c4tech/c4-centreon-server
MAINTAINER jeffrey Brite <jeff@c4tech.com>

# Install centreon poller
RUN yum -y install centreon-poller-centreon-engine

# Install ssh
RUN yum -y install openssh-server openssh-client

